Exercises of css 2.5.1
MaattiiP/matias-pereyra_rosario-web-ui-bootcamp-11-2018 pull request #2
Opened 2018-10-31 20:16 UTC by MaattiiP

Adding exercises of 2.5.1(Include the exercises of 2.3)

2018-11-01 23:23 UTC, ruggero-nardi requested changes
Check those scripts importing external libraries

2018-11-01 23:23 UTC, ruggero-nardi commented on 00-HTML-CSS-basics/exe-css/exe-2.5.1/index.html
> +  <script src="https://www.google-analytics.com/analytics.js" async defer></script>
I've seen this code in other pull requests too. This is importing jQuery and google analytics. Is this being used? If not can you remove it?

2018-11-02 01:45 UTC, MaattiiP commented on 00-HTML-CSS-basics/exe-css/exe-2.5.1/index.html
> +  <script src="https://www.google-analytics.com/analytics.js" async defer></script>
I think they're not being used, so I can get them out. That is right?

2018-11-02 01:49 UTC, ruggero-nardi commented on 00-HTML-CSS-basics/exe-css/exe-2.5.1/index.html
> +  <script src="https://www.google-analytics.com/analytics.js" async defer></script>
Yes, you can remove them

2018-11-02 01:58 UTC, ruggero-nardi approved these changes

2018-11-02 01:59 UTC, merged